// Script to externalize JavaScript from build-static-site.cjs
const fs = require('fs');
const path = require('path');

console.log('🔧 Externalizing JavaScript from build-static-site.cjs...\n');

// Read the build script
const buildScriptPath = path.join(__dirname, 'build-static-site.cjs');
const content = fs.readFileSync(buildScriptPath, 'utf8');
const lines = content.split('\n');

// Find the JavaScript section to externalize (from line after DOMContentLoaded to before </script>)
let jsStart = -1;
let jsEnd = -1;

for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    
    // Find start: line after DOMContentLoaded
    if (line.includes('document.addEventListener(\'DOMContentLoaded\', loadFlightData);')) {
        jsStart = i + 1;
        continue;
    }
    
    // Find end: the </script> tag after line 2200
    if (jsStart > 0 && line.trim() === '</script>' && i > 2200) {
        jsEnd = i;
        break;
    }
}

if (jsStart === -1 || jsEnd === -1) {
    console.error('❌ Could not find JavaScript section to externalize');
    process.exit(1);
}

console.log(`📍 Found JavaScript section:`);
console.log(`   Start: line ${jsStart + 1}`);
console.log(`   End: line ${jsEnd + 1}`);
console.log(`   Total lines: ${jsEnd - jsStart}\n`);

// Extract JavaScript lines and remove 8-space indentation
const jsLines = lines.slice(jsStart, jsEnd);
const cleanedJsLines = jsLines.map(line => {
    // Remove 8 spaces of indentation (2 levels: 4 for script tag, 4 for template literal)
    if (line.startsWith('        ')) {
        return line.substring(8);
    }
    return line;
});

// The JavaScript content needs all the functions
const jsContent = cleanedJsLines.join('\n');

// Now we need to prepend the appJsContent that already exists
const appJsPrefix = `// TMNP Helicopter Tracking - Main Application
// This file is auto-generated by build-static-site.cjs
// Generated: ${new Date().toISOString()}

// Global window variables are set by inline scripts in index.html:
// - window.buildTimestamp
// - window.latestFlightDate  
// - window.embeddedTmnpKml

// Flight data loaded from external JSON file
let flightData = [];

// Load flight data from external JSON file
async function loadFlightData() {
    try {
        const response = await fetch('/master-metadata.json');
        if (!response.ok) {
            throw new Error('Failed to load flight data');
        }
        flightData = await response.json();
        console.log('📊 Loaded', flightData.length, 'flights from external JSON');
        
        // Initialize the application after data is loaded
        initializeApp();
    } catch (error) {
        console.error('Error loading flight data:', error);
        document.body.innerHTML = '<div style="padding: 20px; text-align: center;"><h2>Error Loading Data</h2><p>Unable to load flight data. Please refresh the page.</p></div>';
    }
}

// Initialize application with loaded data
function initializeApp() {
    // Global variables
    let map;
    let currentFlightLayer = null;
    let filteredData = [...flightData];
    let showFilters = false;
    let lastViewedFilename = null;
    
    // UTC to South Africa time conversion
    function utcToSaTime(date, time) {
        if (!date || !time) return '-';
        // date: '2025-05-03', time: '07:31'
        const utc = new Date(\`\${date}T\${time}:00Z\`);
        // South Africa is UTC+2
        const sa = new Date(utc.getTime() + 2 * 60 * 60 * 1000);
        return sa.toISOString().slice(11, 16); // 'HH:MM'
    }

`;

const fullJsContent = appJsPrefix + jsContent;

console.log(`📊 Total JavaScript size: ${fullJsContent.length} bytes (${(fullJsContent.length / 1024).toFixed(1)}KB)\n`);

// Write the output for inspection
const outputPath = path.join(__dirname, 'extracted-app.js');
fs.writeFileSync(outputPath, fullJsContent);
console.log(`✅ Extracted JavaScript saved to: ${outputPath}`);
console.log(`\n📝 Next step: Review the extracted file and then update build-static-site.cjs`);

