// TMNP Helicopter Tracking - Main Application
// This file is auto-generated by build-static-site.cjs
// Generated: 2025-10-19T13:49:39.240Z

// Global window variables are set by inline scripts in index.html:
// - window.buildTimestamp
// - window.latestFlightDate  
// - window.embeddedTmnpKml

// Flight data loaded from external JSON file
let flightData = [];

// Global variables for app state
let map = null;
let currentFlightLayer = null;
let filteredData = [];
let showFilters = false;
let lastViewedFilename = null;

// Load flight data from external JSON file
async function loadFlightData() {
    console.log('🚀 Starting to load flight data...');
    
    // Check for embedded flight data first (for file:// protocol compatibility)
    if (window.embeddedFlightData && Array.isArray(window.embeddedFlightData)) {
        console.log('📊 Using embedded flight data');
        flightData = window.embeddedFlightData;
        console.log('📊 Loaded', flightData.length, 'flights from embedded data');
        
        // Initialize the application after data is loaded
        console.log('🎯 Calling initializeApp() with embedded data...');
        initializeApp();
        return;
    }
    
    // Try to load from external JSON file
    try {
        console.log('📡 Fetching /master-metadata.json...');
        const response = await fetch('/master-metadata.json');
        if (!response.ok) {
            throw new Error('Failed to load flight data');
        }
        const data = await response.json();
        flightData = data.flights || data; // Handle both {flights: [...]} and [...] formats
        console.log('📊 Loaded', flightData.length, 'flights from external JSON');
        
        // Initialize the application after data is loaded
        console.log('🎯 Calling initializeApp() with real data...');
        initializeApp();
    } catch (error) {
        console.error('Error loading flight data:', error);
        // Use empty dataset and still initialize for graceful degradation
        console.log('Could not load external data, using empty dataset for local viewing');
        flightData = [];
        console.log('🎯 Calling initializeApp() with empty data...');
        initializeApp();
    }
}

// UTC to South Africa time conversion
function utcToSaTime(date, time) {
    if (!date || !time) return '-';
    // date: '2025-05-03', time: '07:31'
    const utc = new Date(`${date}T${time}:00Z`);
    // South Africa is UTC+2
    const sa = new Date(utc.getTime() + 2 * 60 * 60 * 1000);
    return sa.toISOString().slice(11, 16); // 'HH:MM'
}

// Initialize application with loaded data
function initializeApp() {
    console.log('🎯 initializeApp() called with', flightData.length, 'flights');
    
    // Initialize global variables
    filteredData = Array.isArray(flightData) ? [...flightData] : [];
    
    // Actually call the initialization functions
    initializeMap();
    populateRegistrationDropdown();
    populateOwnerDropdown();
    setupEventListeners(); // Set up filter event listeners (registration, owner, date filters)
    renderTable();
}

function showConnectionError() {
    const mapContainer = document.getElementById('map');
    mapContainer.innerHTML = `
        <div style="display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100%; background: #f8f9fa; border-radius: 8px; padding: 40px; text-align: center;">
            <div style="font-size: 48px; margin-bottom: 16px;">🌐</div>
            <h3 style="color: #dc3545; margin-bottom: 12px;">Internet Connection Required</h3>
            <p style="color: #6c757d; margin-bottom: 16px; max-width: 400px;">
                The interactive map requires an internet connection to load mapping libraries. 
                Please check your connection and refresh the page.
            </p>
            <div style="background: #fff3cd; border: 1px solid #ffeaa7; border-radius: 8px; padding: 16px; margin-top: 16px; max-width: 400px;">
                <strong>Note:</strong> You can still view all flight data in the table below, 
                download KML files, and generate violation reports without the map.
            </div>
            <button onclick="location.reload()" style="margin-top: 16px; padding: 8px 16px; background: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer;">
                🔄 Retry
            </button>
        </div>
    `;
}

// Load TMNP boundary from external KML file
function loadTmnpBoundary() {
    if (typeof omnivore === 'undefined') {
        console.error('❌ Omnivore not available, cannot load TMNP boundary');
        return;
    }
    
    console.log('📄 Loading TMNP boundary from ./tmnp.kml...');
    
    try {
        window.tmnpLayer = omnivore.kml('./tmnp.kml', null, L.geoJson(null, {
            style: function(feature) {
                return {
                    color: '#ff0000',
                    weight: 3,
                    opacity: 0.7,
                    fillColor: '#ff0000',
                    fillOpacity: 0.25
                };
            }
        })).addTo(map);
        
        window.tmnpLayer.on('ready', function() {
            console.log('✅ TMNP boundary loaded successfully from external file');
            // Fit map to show TMNP boundary if no flights are loaded yet
            if (filteredData.length === 0) {
                map.fitBounds(window.tmnpLayer.getBounds(), { padding: [20, 20] });
            }
        });
        
        window.tmnpLayer.on('error', function(e) {
            console.error('❌ Error loading TMNP boundary:', e);
        });
    } catch (error) {
        console.error('❌ Failed to load TMNP boundary:', error);
    }
}

function initializeMap() {
    console.log('🗺️ Initializing map...');
    console.log('Leaflet available:', typeof L);
    console.log('Omnivore available:', typeof omnivore);
    console.log('Map container exists:', document.getElementById('map'));
    
    if (typeof L === 'undefined') {
        console.error('❌ Leaflet not available, showing connection error');
        showConnectionError();
        return;
    }
    
    if (typeof omnivore === 'undefined') {
        console.error('❌ Omnivore not available, showing connection error');
        showConnectionError();
        return;
    }
    
    // Initialize map centered on Cape Town
    map = L.map('map').setView([-33.9249, 18.4241], 10);
    console.log('Map created:', map);
    
    // Add OpenStreetMap tiles
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '© OpenStreetMap contributors'
    }).addTo(map);
    console.log('Tile layer added to map');
    
    // Add TMNP boundary from embedded KML content (works with file:// protocol)
    console.log('🔍 Checking for embedded TMNP KML...');
    console.log('window.embeddedTmnpKml exists:', !!window.embeddedTmnpKml);
    console.log('window.embeddedTmnpKml length:', window.embeddedTmnpKml ? window.embeddedTmnpKml.length : 0);
    
    if (window.embeddedTmnpKml) {
        console.log('✅ Embedded TMNP KML found, parsing...');
        // Parse the embedded KML and create layers directly
        const parser = new DOMParser();
        const kmlDoc = parser.parseFromString(window.embeddedTmnpKml, 'text/xml');
        
        // Create a layer group for the TMNP boundary
        window.tmnpLayer = L.layerGroup().addTo(map);
        
        // Parse KML features and add to map
        const polygons = kmlDoc.querySelectorAll('Polygon');
        console.log('🔍 Found', polygons.length, 'polygons in TMNP KML');
        let bounds = null;
        
        polygons.forEach((polygon, idx) => {
            console.log('🔍 Processing polygon', idx + 1, 'of', polygons.length);
            const outerBoundary = polygon.querySelector('outerBoundaryIs LinearRing coordinates');
            if (outerBoundary) {
                const coordsText = outerBoundary.textContent.trim();
                console.log('🔍 Coordinate text length:', coordsText.length);
                // Split by any whitespace (space, tab, newline)
                const coords = coordsText.split(/\s+/).map(coord => {
                    const [lon, lat] = coord.split(',').map(parseFloat);
                    return [lat, lon];
                }).filter(coord => !isNaN(coord[0]) && !isNaN(coord[1]));
                
                if (coords.length > 0) {
                    console.log('✅ Creating polygon with', coords.length, 'coordinates');
                    const poly = L.polygon(coords, {
                        color: '#ff0000',
                        weight: 3,
                        opacity: 0.7,
                        fillColor: '#ff0000',
                        fillOpacity: 0.25
                    });
                    window.tmnpLayer.addLayer(poly);
                    console.log('✅ Polygon added to map');
                    
                    // Calculate bounds for the whole park
                    const polyBounds = L.latLngBounds(coords);
                    if (!bounds) {
                        bounds = polyBounds;
                    } else {
                        bounds.extend(polyBounds);
                    }
                }
            }
        });
        
        if (bounds) {
            console.log('TMNP boundary loaded successfully from embedded data');
            map.fitBounds(bounds, { padding: [20, 20] });
        } else {
            console.log('No valid polygon data found in TMNP KML');
        }
    } else {
        console.log('No embedded TMNP KML data found, loading externally...');
        // Fallback: Load TMNP boundary from external KML file
        loadTmnpBoundary();
    }
    
    // Show initial instruction overlay
    const instructionDiv = document.createElement('div');
    instructionDiv.id = 'instructionOverlay';
    instructionDiv.innerHTML = '<div style="text-align: center; line-height: 1.4;"><div style="font-size: 18px; margin-bottom: 8px;">🗺️ Flight Tracking Map</div><div style="font-size: 14px; margin-bottom: 12px;">Scroll down to view flights</div><div style="font-size: 12px; color: #ccc;">Click the 👀 button on any flight to see its path</div></div>';
    instructionDiv.style.cssText = 'position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); background: rgba(0,0,0,0.8); color: white; padding: 25px 35px; border-radius: 12px; z-index: 1000; font-size: 14px; font-weight: 500; box-shadow: 0 6px 20px rgba(0,0,0,0.4); max-width: 300px;';
    map.getContainer().appendChild(instructionDiv);
    
    // Disable map scroll zoom while instruction overlay is visible
    map.scrollWheelZoom.disable();
}

function populateRegistrationDropdown() {
    const registrationSelect = document.getElementById('registrationFilter');
    
    // Get unique registrations from flight data
    const uniqueRegistrations = [...new Set(flightData.map(flight => flight.registration))]
        .filter(reg => reg && reg.trim()) // Filter out empty/null registrations
        .sort(); // Sort alphabetically
    
    // Clear existing options (except "All Registrations")
    registrationSelect.innerHTML = '<option value="">All Registrations</option>';
    
    // Add each unique registration as an option
    uniqueRegistrations.forEach(registration => {
        const option = document.createElement('option');
        option.value = registration;
        option.textContent = registration;
        registrationSelect.appendChild(option);
    });
    
    console.log(`✅ Populated registration dropdown with ${uniqueRegistrations.length} unique registrations`);
}

function populateOwnerDropdown() {
    const ownerSelect = document.getElementById('ownerFilter');
    
    // Get unique owners from flight data
    const uniqueOwners = [...new Set(flightData.map(flight => flight.owner))]
        .filter(owner => owner && owner.trim()) // Filter out empty/null owners
        .sort(); // Sort alphabetically
    
    // Clear existing options (except "All Owners")
    ownerSelect.innerHTML = '<option value="">All Owners</option>';
    
    // Add each unique owner as an option
    uniqueOwners.forEach(owner => {
        const option = document.createElement('option');
        option.value = owner;
        option.textContent = owner;
        ownerSelect.appendChild(option);
    });
    
    console.log(`✅ Populated owner dropdown with ${uniqueOwners.length} unique owners`);
}

function setupEventListeners() {
    // Populate dropdowns
    populateRegistrationDropdown();
    populateOwnerDropdown();
    
    // Set initial date range
    if (flightData.length > 0) {
        const dates = flightData.map(f => f.date).sort();
        document.getElementById('dateStart').value = dates[0];
        document.getElementById('dateEnd').value = dates[dates.length - 1];
    }
    
    // Filter input events
    document.getElementById('registrationFilter').addEventListener('change', applyFilters);
    document.getElementById('ownerFilter').addEventListener('change', applyFilters);
    document.getElementById('dateStart').addEventListener('change', applyFilters);
    document.getElementById('dateEnd').addEventListener('change', applyFilters);
    
    // Update clear button visibility on input/change
    document.getElementById('registrationFilter').addEventListener('change', () => {
        const hasFilters = document.getElementById('registrationFilter').value || 
                          document.getElementById('ownerFilter').value ||
                          document.getElementById('dateStart').value || 
                          document.getElementById('dateEnd').value;
        document.querySelector('.clear-btn').style.display = hasFilters ? 'block' : 'none';
    });
    
    document.getElementById('ownerFilter').addEventListener('change', () => {
        const hasFilters = document.getElementById('registrationFilter').value || 
                          document.getElementById('ownerFilter').value ||
                          document.getElementById('dateStart').value || 
                          document.getElementById('dateEnd').value;
        document.querySelector('.clear-btn').style.display = hasFilters ? 'block' : 'none';
    });
    
    ['dateStart', 'dateEnd'].forEach(id => {
        document.getElementById(id).addEventListener('input', () => {
            const hasFilters = document.getElementById('registrationFilter').value || 
                              document.getElementById('ownerFilter').value ||
                              document.getElementById('dateStart').value || 
                              document.getElementById('dateEnd').value;
            document.querySelector('.clear-btn').style.display = hasFilters ? 'block' : 'none';
        });
    });
}

function applyFilters() {
    const registration = document.getElementById('registrationFilter').value;
    const owner = document.getElementById('ownerFilter').value;
    const dateStart = document.getElementById('dateStart').value;
    const dateEnd = document.getElementById('dateEnd').value;
    
    filteredData = flightData.filter(flight => {
        const regMatch = !registration || flight.registration === registration;
        const ownerMatch = !owner || flight.owner === owner;
        const dateMatch = (!dateStart || flight.date >= dateStart) && (!dateEnd || flight.date <= dateEnd);
        return regMatch && ownerMatch && dateMatch;
    });
    
    renderTable();
    updateSummary();
}

// Toggle filters visibility
function toggleFilters() {
    showFilters = !showFilters;
    const content = document.getElementById('filtersContent');
    const button = document.querySelector('.toggle-btn');
    const clearBtn = document.querySelector('.clear-btn');
    const filtersCard = document.getElementById('filtersCard');
    
    if (showFilters) {
        content.style.display = 'flex';
        button.textContent = 'Hide Filters';
        filtersCard.classList.remove('collapsed');
    } else {
        content.style.display = 'none';
        button.textContent = 'Show Filters';
        filtersCard.classList.add('collapsed');
    }
    
    // Show/hide clear button based on active filters
    const hasFilters = document.getElementById('registrationFilter').value || 
                      document.getElementById('ownerFilter').value ||
                      document.getElementById('dateStart').value || 
                      document.getElementById('dateEnd').value;
    clearBtn.style.display = hasFilters ? 'block' : 'none';
}

function clearFilters() {
    document.getElementById('registrationFilter').value = '';
    document.getElementById('ownerFilter').value = '';
    document.getElementById('dateStart').value = '';
    document.getElementById('dateEnd').value = '';
    filteredData = [...flightData];
    renderTable();
    updateSummary();
    
    // Hide clear button
    document.querySelector('.clear-btn').style.display = 'none';
    // Update filter summary
    document.getElementById('filterSummary').textContent = 'All flights';
}

function updateSummary() {
    const uniqueHelicopters = new Set(filteredData.map(f => f.registration)).size;
    const dates = filteredData.map(f => f.date).sort();
    const startDate = dates.length > 0 ? dates[0] : '';
    const endDate = dates.length > 0 ? dates[dates.length - 1] : '';
    
    // Update summary cards
    const flightsEl = document.getElementById('flightsCount');
    const helisEl = document.getElementById('helicoptersCount');
    const startEl = document.getElementById('dateStartCard');
    const endEl = document.getElementById('dateEndCard');
    if (flightsEl) flightsEl.textContent = filteredData.length;
    if (helisEl) helisEl.textContent = uniqueHelicopters;
    if (startEl) startEl.textContent = startDate || '-';
    if (endEl) endEl.textContent = endDate || '-';
    
    // Update filter summary
    const filterSummary = document.getElementById('filterSummary');
    if (filteredData.length === flightData.length) {
        filterSummary.textContent = 'All flights';
    } else {
        filterSummary.textContent = filteredData.length + ' of ' + flightData.length + ' flights';
    }
    
    // Show/hide clear button
    const hasFilters = document.getElementById('registrationFilter').value || 
                      document.getElementById('ownerFilter').value ||
                      document.getElementById('dateStart').value || 
                      document.getElementById('dateEnd').value;
    document.querySelector('.clear-btn').style.display = hasFilters ? 'block' : 'none';
}

function renderTable() {
    const container = document.getElementById('tableContainer');
    
    if (filteredData.length === 0) {
        container.innerHTML = '<div class="error">No flights found matching the current filters.</div>';
        return;
    }
    
    // Sort by date (newest first)
    const sortedData = [...filteredData].sort((a, b) => new Date(b.date) - new Date(a.date));
    
    const tableHTML = `
        <h2>Airspace Violations</h2>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Takeoff time (SA)</th>
                    <th>Registration</th>
                    <th>Owner</th>
                    <th>Filename</th>
                    <th>KML</th>
                    <th>Size</th>
                    <th>View Flight</th>
                    <th>Take action</th>
                </tr>
            </thead>
            <tbody>
                ${sortedData.map(flight => `
                    <tr id="flight-${flight.filename}" class="flight-row" onclick="viewFlight('${flight.filename}')" style="${lastViewedFilename === flight.filename ? 'background: #e6f7ff;' : ''}">
                        <td style="white-space: nowrap; min-width: 100px; width: 100px;">${flight.date || '-'}</td>
                        <td>${utcToSaTime(flight.date, flight.time)}</td>
                        <td>${flight.registration || '-'}</td>
                        <td style="white-space: nowrap; min-width: 150px;">${flight.owner || '-'}</td>
                        <td style="font-size: 12px;">${flight.filename || '-'}</td>
                        <td style="text-align: center;">
                            <a href="https://raw.githubusercontent.com/werneravr/heli-map/main/backend/uploads/${flight.filename}" download="${flight.filename}" title="Download KML" style="font-size: 1.3em; color: #007bff; text-decoration: none; cursor: pointer;" onclick="event.stopPropagation(); downloadKML('${flight.filename}'); return false;">⬇️</a>
                        </td>
                        <td style="text-align: center;">${flight.fileSizeMB ? flight.fileSizeMB + ' MB' : '-'}</td>
                        <td>
                            <button onclick="event.stopPropagation(); loadFlightOnMap('${flight.filename}')" style="padding: 4px 12px; border-radius: 4px; background: #007bff; color: #fff; border: none; cursor: pointer; font-size: 1.2em;" title="View on map">👀</button>
                        </td>
                        <td>
                            <button onclick="event.stopPropagation(); reportFlight('${flight.filename}')" style="padding: 6px 12px; border-radius: 4px; background: #dc3545; color: #fff; border: none; cursor: pointer; font-size: 18px; font-weight: 600; display: flex; align-items: center; gap: 4px;" title="Generate violation report">👮‍♂️</button>
                        </td>
                    </tr>
                `).join('')}
            </tbody>
        </table>
    `;
    
    container.innerHTML = tableHTML;
    updateSummary();
}


function loadFlightOnMap(filename) {
    const startTime = performance.now();
    const flight = flightData.find(f => f.filename === filename);
    if (!flight) return;
    
    console.log('🚀 Starting flight load for:', filename);
    console.log('📊 File size:', flight.fileSizeMB, 'MB');
    
    // Set the last viewed filename for highlighting
    lastViewedFilename = filename;
    
    // Show and populate the viewing flight information box
    showViewingFlight(flight);
    
    // Scroll to top to show the map update
    window.scrollTo({ top: 0, behavior: 'smooth' });
    
    // Re-render table to show highlighting
    renderTable();
    
    // Remove previous flight layer
    if (currentFlightLayer) {
        map.removeLayer(currentFlightLayer);
    }
    
    // Remove instruction overlay if it exists
    const instructionOverlay = document.getElementById('instructionOverlay');
    if (instructionOverlay) {
        instructionOverlay.remove();
        // Re-enable map scroll zoom now that user is interacting with flights
        map.scrollWheelZoom.enable();
    }
    
     // Show loading indicator in center of map
     const loadingDiv = document.createElement('div');
     loadingDiv.innerHTML = '<span class="helicopter-loader">🚁</span> Loading flight path...';
     loadingDiv.style.cssText = 'position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); background: rgba(0,0,0,0.8); color: white; padding: 20px 30px; border-radius: 10px; z-index: 1000; font-size: 16px; font-weight: bold; box-shadow: 0 4px 12px rgba(0,0,0,0.3);';
     map.getContainer().appendChild(loadingDiv);
    
    // Try optimized KML first, fallback to original KML from GitHub
    const optimizedFilename = filename.replace('.kml', '-opt.kml');
    const optimizedUrl = './kml-optimised/' + optimizedFilename;
    const originalUrl = 'https://raw.githubusercontent.com/werneravr/heli-map/main/backend/uploads/' + filename;
    
    console.log('📍 Checking optimized KML first:', optimizedUrl);
    
    const downloadStartTime = performance.now();
    
    // Try to load from optimized KML first (much faster and smaller)
    currentFlightLayer = omnivore.kml(optimizedUrl)
        .on('ready', function() {
            const downloadTime = performance.now() - downloadStartTime;
            const totalTime = performance.now() - startTime;
            
            console.log('✅ Optimized KML loaded successfully!');
            console.log('⚡ Performance:', {
                downloadTime: (downloadTime / 1000).toFixed(2) + 's',
                totalTime: (totalTime / 1000).toFixed(2) + 's',
                fileSize: flight.fileSizeMB + 'MB',
                speed: (flight.fileSizeMB / (downloadTime / 1000)).toFixed(2) + 'MB/s'
            });
            
            // Remove loading indicator
            if (loadingDiv.parentNode) {
                loadingDiv.parentNode.removeChild(loadingDiv);
            }
            
            this.setStyle(() => ({
                color: '#0000ff',
                weight: 4,
                opacity: 0.8
            }));
            
            // Fit bounds to both TMNP and the new KML if both are present
            if (window.tmnpLayer) {
                const group = L.featureGroup([window.tmnpLayer, this]);
                map.fitBounds(group.getBounds(), { padding: [20, 20] });
            } else {
                map.fitBounds(this.getBounds(), { padding: [20, 20] });
            }
        })
        .on('error', function(error) {
            console.log('⚠️ Optimized KML failed, trying original KML...');
            console.log('❌ Optimized KML error:', error);
            
            // Fallback to original KML
            const originalStartTime = performance.now();
            
            omnivore.kml(originalUrl)
                .on('ready', function() {
                    const originalDownloadTime = performance.now() - originalStartTime;
                    const totalTime = performance.now() - startTime;
                    
                    console.log('✅ Original KML loaded successfully!');
                    console.log('⚡ Performance:', {
                        originalDownloadTime: (originalDownloadTime / 1000).toFixed(2) + 's',
                        totalTime: (totalTime / 1000).toFixed(2) + 's',
                        fileSize: flight.fileSizeMB + 'MB',
                        originalSpeed: (flight.fileSizeMB / (originalDownloadTime / 1000)).toFixed(2) + 'MB/s'
                    });
                    
                    // Remove loading indicator
                    if (loadingDiv.parentNode) {
                        loadingDiv.parentNode.removeChild(loadingDiv);
                    }
                    
                    currentFlightLayer = this;
                    
                    this.setStyle(() => ({
                        color: '#0000ff',
                        weight: 4,
                        opacity: 0.8
                    }));
                    
                    // Fit bounds to both TMNP and the new KML if both are present
                    if (window.tmnpLayer) {
                        const group = L.featureGroup([window.tmnpLayer, this]);
                        map.fitBounds(group.getBounds(), { padding: [20, 20] });
                    } else {
                        map.fitBounds(this.getBounds(), { padding: [20, 20] });
                    }
                })
                .on('error', function(originalError) {
                    const totalTime = performance.now() - startTime;
                    console.error('❌ Both optimized and original KML load failed:', {
                        optimizedError: error,
                        originalError: originalError,
                        totalTime: (totalTime / 1000).toFixed(2) + 's'
                    });
                    
                    if (loadingDiv.parentNode) {
                        loadingDiv.parentNode.removeChild(loadingDiv);
                    }
                    
                    // Show error message in map
                    const errorDiv = document.createElement('div');
                    errorDiv.innerHTML = '<div style="text-align: center; color: #dc3545; padding: 20px; font-size: 14px;"><strong>⚠️ Unable to load flight path</strong><br>Both optimized and original KML sources failed.<br>Total time: ' + (totalTime / 1000).toFixed(2) + 's</div>';
                    errorDiv.style.cssText = 'position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); background: rgba(255,255,255,0.9); border-radius: 8px; z-index: 1000;';
                    map.getContainer().appendChild(errorDiv);
                    setTimeout(() => {
                        if (errorDiv.parentNode) {
                            errorDiv.parentNode.removeChild(errorDiv);
                        }
                    }, 5000);
                })
                .addTo(map);
        })
        .addTo(map);
    
    closeModal();
}

function reportFlight(filename) {
    const modal = document.getElementById('reportModal');
    const content = document.getElementById('reportModalContent');
    
    // Find the flight by filename
    const flight = flightData.find(f => f.filename === filename);
    if (!flight) {
        console.error('Flight not found for filename:', filename);
        return;
    }
    
    const registration = flight.registration || 'UNKNOWN';
    const owner = flight.owner || 'Private owner';
    const date = flight.date || 'UNKNOWN DATE';
    const imageFilename = flight.filename ? flight.filename.replace('.kml', '.png') : null;
    const imagePath = imageFilename ? 'https://media.githubusercontent.com/media/werneravr/heli-map/main/backend/flight-maps/' + imageFilename : null;
    
    const reportText = 'It appears that a helicopter, registration ' + registration + ' (' + owner + '), entered restricted NP17 airspace over Table Mountain on ' + date + '.\n\nThe National Environmental Management Protected Areas Act (NEMPAA NP17) clearly states that aircraft are prohibited from flying over TMNP at any height below 6070FT (~1850m). Doing so without authorisation is an offense with fines up to R5 million or imprisonment for up to 10 years, and can result in the suspension of licenses by the Civil Aviation Authority.\n\nNEMPAA (NP17) and these penalties are in place to protect the park\'s natural environment and ensure compliance with airspace regulations.';
    
    content.innerHTML = `
        <div style="margin-bottom: 20px; border-bottom: 1px solid #eee; padding-bottom: 16px;">
            <h2 style="margin: 0; color: #333;">Flight Violation Report</h2>
        </div>

        <!-- Flight Map Image -->
        <div style="margin-bottom: 24px; text-align: center;">
            ${imagePath ? `
                <div style="position: relative; display: inline-block;">
                    <img
                        src="${imagePath}"
                        alt="Flight map for ${registration}"
                        style="width: 320px; height: 320px; object-fit: contain; border-radius: 8px; border: 1px solid #ddd;"
                        onerror="this.style.display='none'; this.nextElementSibling.style.display='block';"
                    />
                    <div style="display: none; color: #666; font-style: italic;">Flight map image not available</div>
                    <button
                        onclick="downloadPNG('${imageFilename}')"
                        style="position: absolute; bottom: 8px; right: 8px; padding: 6px 12px; background-color: rgba(40, 167, 69, 0.9); color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 12px; font-weight: 600; backdrop-filter: blur(4px); box-shadow: 0 2px 4px rgba(0,0,0,0.3);"
                        title="Save flight map image"
                    >
                        💾 Save Image
                    </button>
                </div>
            ` : `
                <div style="color: #666; font-style: italic; padding: 40px;">Flight map image not available</div>
            `}
        </div>

        <!-- Report Information -->
        <div style="margin-bottom: 24px;">
            <!-- Report Text -->
            <div style="background-color: #f8f9fa; padding: 16px; border-radius: 8px; border: 1px solid #dee2e6; margin-bottom: 16px; font-family: monospace; font-size: 14px; line-height: 1.5; text-align: left; position: relative;">
                ${reportText}
                <button
                    onclick="copyReportText('${reportText}')"
                    style="position: absolute; bottom: 8px; right: 8px; padding: 4px 8px; background-color: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 12px; font-weight: 600;"
                    title="Copy report text to clipboard"
                >
                    📋 Copy text
                </button>
            </div>

            <!-- Reporting Information -->
            <div style="background-color: #fff3cd; border: 1px solid #ffeaa7; border-radius: 8px; padding: 16px; margin-bottom: 16px;">
                <h3 style="margin: 0 0 12px 0; color: #856404; font-size: 16px;">📧 How to Report This Violation</h3>
                
                <div style="margin-bottom: 12px;">
                    <strong style="color: #856404;">South African Civil Aviation Authority (SACAA):</strong><br/>
                    <span style="font-family: monospace; font-size: 13px;">enforcement@caa.co.za</span>
                </div>
                
                <div style="margin-bottom: 12px;">
                    <strong style="color: #856404;">South African National Parks (SanParks):</strong><br/>
                    <span style="font-family: monospace; font-size: 13px;">TableM@sanparks.org</span>
                </div>
                
                <div style="margin-bottom: 12px;">
                    <strong style="color: #856404;">Helicopter Company Contact:</strong><br/>
                    <span style="font-size: 13px; white-space: pre-line;">${flight.contact || owner || 'Contact information not available'}</span>
                </div>
            </div>

            <!-- Download Instructions -->
            <div style="background-color: #d1ecf1; border: 1px solid #bee5eb; border-radius: 8px; padding: 16px;">
                <h3 style="margin: 0 0 12px 0; color: #0c5460; font-size: 16px;">📁 Evidence Files</h3>
                
                <div style="margin-bottom: 8px;">
                    <strong style="color: #0c5460;">KML Flight Data:</strong><br/>
                    <span style="font-size: 13px;">Click the "⬇️ Download KML" button below to download the flight path data</span>
                </div>
                
                <div style="margin-bottom: 8px;">
                    <strong style="color: #0c5460;">PNG Flight Map:</strong><br/>
                    <span style="font-size: 13px;">Click the "💾 Save Image" button on the map above to download the visual evidence</span>
                </div>
                
                <div style="font-size: 12px; color: #0c5460; font-style: italic; margin-top: 8px;">
                    Include both files when reporting to authorities for complete evidence.
                </div>
            </div>
        </div>

        <!-- Action Buttons -->
        <div style="text-align: center; padding-top: 16px; border-top: 1px solid #eee;">
            <button onclick="downloadKML('${flight.filename}')" style="padding: 8px 16px; background-color: #28a745; color: white; border: none; border-radius: 6px; cursor: pointer; font-size: 14px; font-weight: 600; margin-right: 8px;">
                ⬇️ Download KML
            </button>
            <button onclick="closeReportModal()" style="padding: 10px 24px; background-color: #6c757d; color: white; border: none; border-radius: 6px; cursor: pointer; font-size: 16px; font-weight: 600;">
                Close
            </button>
        </div>
    `;
    
    modal.style.display = 'block';
}

function closeReportModal() {
    document.getElementById('reportModal').style.display = 'none';
}

function copyReportText(text) {
    if (navigator.clipboard) {
        navigator.clipboard.writeText(text).then(() => {
            alert('Report text copied to clipboard!');
        }).catch(() => {
            alert('Report text:\n\n"' + text + '"\n\n(Please copy manually)');
        });
    } else {
        alert('Report text:\n\n"' + text + '"\n\n(Please copy manually)');
    }
}

function downloadPNG(filename) {
    const url = 'https://media.githubusercontent.com/media/werneravr/heli-map/main/backend/flight-maps/' + filename;
    
    try {
        const button = event.target;
        const originalText = button.innerHTML;
        button.innerHTML = '⬇️ Downloading...';
        button.disabled = true;
        
        fetch(url)
            .then(response => {
                if (!response.ok) {
                    throw new Error('HTTP error! status: ' + response.status);
                }
                return response.blob();
            })
            .then(blob => {
                const blobUrl = URL.createObjectURL(blob);
                const link = document.createElement('a');
                link.href = blobUrl;
                link.download = filename;
                link.click();
                URL.revokeObjectURL(blobUrl);
                
                button.innerHTML = '✅ Downloaded!';
                setTimeout(() => {
                    button.innerHTML = originalText;
                    button.disabled = false;
                }, 2000);
            })
            .catch(error => {
                console.error('Download error:', error);
                alert('Failed to download image. Please try again.');
                button.innerHTML = '💾 Save Image';
                button.disabled = false;
            });
    } catch (error) {
        console.error('Download error:', error);
        alert('Failed to download image. Please try again.');
    }
}

function exportCSV() {
    const headers = ['Date', 'UTC Time', 'SA Time', 'Registration', 'Owner', 'Filename', 'Size (MB)'];
    const csvContent = [
        headers.join(','),
        ...filteredData.map(flight => [
            flight.date || '',
            flight.time || '',
            utcToSaTime(flight.date, flight.time),
            flight.registration || '',
            flight.owner || '',
            flight.filename || '',
            flight.fileSizeMB || ''
        ].join(','))
    ].join('\n');
    
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'tmnp-flights-' + new Date().toISOString().split('T')[0] + '.csv';
    a.click();
    window.URL.revokeObjectURL(url);
}

// Close modal when clicking outside
window.onclick = function(event) {
    const reportModal = document.getElementById('reportModal');
    if (event.target === reportModal) {
        closeReportModal();
    }
}

// KML download function
async function downloadKML(filename) {
    const url = 'https://raw.githubusercontent.com/werneravr/heli-map/main/backend/uploads/' + filename;
    
    try {
        // Show loading indicator
        const button = event.target;
        const originalText = button.innerHTML;
        button.innerHTML = '⏳ Downloading...';
        button.disabled = true;
        
        // Fetch the file content
        const response = await fetch(url);
        if (!response.ok) {
            throw new Error('HTTP error! status: ' + response.status);
        }
        
        const blob = await response.blob();
        
        // Create download link
        const downloadUrl = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = downloadUrl;
        link.download = filename;
        link.style.display = 'none';
        
        // Trigger download
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        
        // Clean up
        window.URL.revokeObjectURL(downloadUrl);
        
        // Restore button
        button.innerHTML = originalText;
        button.disabled = false;
        
        // Show success message
        const successText = button.innerHTML;
        button.innerHTML = '✅ Downloaded!';
        setTimeout(() => {
            button.innerHTML = successText;
        }, 2000);
        
    } catch (error) {
        console.error('Download failed:', error);
        
        // Restore button
        const button = event.target;
        button.innerHTML = '⬇️';
        button.disabled = false;
        
        // Fallback: open in new tab
        window.open(url, '_blank');
        
        alert('Download failed. Opening file in new tab instead.');
    }
}

// Home, Contact, and FAQ functions
function showHome() {
    // Hide all pages and show main content
    document.getElementById('contactPage').style.display = 'none';
    document.getElementById('faqPage').style.display = 'none';
    document.querySelector('.main-content').style.display = 'block';
}

function showContact() {
    // Hide main content and FAQ page, show contact page
    document.querySelector('.main-content').style.display = 'none';
    document.getElementById('faqPage').style.display = 'none';
    document.getElementById('contactPage').style.display = 'flex';
}

function revealEmail() {
    const button = document.getElementById('emailButton');
    const emailDiv = document.getElementById('emailAddress');
    
    // Animate button disappearing
    button.style.opacity = '0';
    button.style.transform = 'scale(0.8)';
    
    // After button animation, show email
    setTimeout(() => {
        button.style.display = 'none';
        emailDiv.style.display = 'block';
        
        // Animate email appearing
        setTimeout(() => {
            emailDiv.style.opacity = '1';
        }, 50);
    }, 300);
}

function showFAQ() {
    // Hide main content and contact page, show FAQ page
    document.querySelector('.main-content').style.display = 'none';
    document.getElementById('contactPage').style.display = 'none';
    document.getElementById('faqPage').style.display = 'flex';
    
    // Populate FAQ content
    populateFAQ();
}

function populateFAQ() {
    const faqContent = document.getElementById('faqContent');
    const faqs = [
        {
            question: 'Why does this page exist?',
            answer: '<div><p>This page was created to help protect the natural tranquillity of Table Mountain National Park (TMNP). Helicopter flights can disturb wildlife, hikers, and the serenity of this unique environment.</p><p>Our goal is to:</p><ul><li>Monitor and highlight helicopter activity over the park, especially those entering airspace where they should not be.</li><li>Inform the public about the extent of unauthorised or disruptive flights.</li><li>Encourage accountability and compliance with airspace regulations.</li></ul><p>In short: This is not about naming and shaming pilots or operators – it is about preserving the peace of our park for everyone who loves it, from hikers to wildlife.</p></div>'
        },
        {
            question: 'What does the law say?',
            answer: '<div><p>The law is very clear. Aircraft need permission to fly over Table Mountain National Park (TMNP). If they fly there without permission, there are severe penalties.</p><p>See the National Environmental Management: Protected Areas Act (NEMPAA NP17), which clearly state that aircraft are prohibited from flying over TMNP at any height below 6070FT (~1850m).</p><ul><li><a href="./NEMPAA.pdf" target="_blank" rel="noopener noreferrer" download>NEMPAA (PDF)</a></li><li><a href="./NP17.pdf" target="_blank" rel="noopener noreferrer" download>TMNP boundary NP17 (PDF)</a></li></ul></div>'
        },
        {
            question: 'What are the penalties?',
            answer: '<div><p>Violations of the NEMPAA NP17 regulations can result in:</p><ul><li><strong>Fines:</strong> Up to R5 million or imprisonment for up to 10 years</li><li><strong>License suspension:</strong> Civil Aviation Authority can suspend pilot licenses</li><li><strong>Operator penalties:</strong> Helicopter operators can face additional sanctions</li><li><strong>Environmental impact:</strong> Disturbance to wildlife and park visitors</li></ul><p>These penalties are designed to protect the park natural environment and ensure compliance with airspace regulations.</p></div>'
        },
        {
            question: 'How is this data collected?',
            answer: '<div><p>Flight data is collected through:</p><ul><li><strong>ADS-B tracking:</strong> Automatic Dependent Surveillance-Broadcast signals from aircraft</li><li><strong>Flight tracking systems:</strong> Publicly available flight tracking data</li><li><strong>Manual verification:</strong> Cross-referencing with official flight plans and permissions</li><li><strong>Geographic analysis:</strong> Determining if flights entered restricted airspace</li></ul><p>All data is publicly available and collected through legitimate means. No private or confidential information is accessed.</p></div>'
        },
        {
            question: 'What should I do if I see a violation?',
            answer: '<div><p>If you witness a helicopter flying over Table Mountain National Park without permission:</p><ul><li><strong>Report to SACAA:</strong> South African Civil Aviation Authority (enforcement@caa.co.za)</li><li><strong>Report to SanParks:</strong> Table Mountain National Park management (TableM@sanparks.org)</li><li><strong>Document evidence:</strong> Take photos/videos if safe to do so</li><li><strong>Note details:</strong> Time, location, aircraft registration if visible</li></ul><p>Use the report function on this site to generate a formal complaint with all relevant details.</p></div>'
        },
        {
            question: 'Is this data accurate?',
            answer: '<div><p>We strive for accuracy by:</p><ul><li><strong>Multiple data sources:</strong> Cross-referencing different tracking systems</li><li><strong>Manual verification:</strong> Checking flight plans and permissions</li><li><strong>Regular updates:</strong> Keeping data current and relevant</li><li><strong>Transparency:</strong> Showing our methodology and data sources</li></ul><p>However, flight tracking data can sometimes have inaccuracies. If you believe there is an error, please contact us with supporting evidence.</p></div>'
        }
    ];
    
    faqContent.innerHTML = faqs.map((faq, idx) => 
        '<div class="faq-card">' +
            '<button class="faq-button" onclick="toggleFAQ(' + idx + ')" aria-expanded="false" aria-controls="faq-answer-' + idx + '">' +
                '<span class="faq-question-text">' + faq.question + '</span>' +
                '<span class="faq-icon" id="faq-icon-' + idx + '">+</span>' +
            '</button>' +
            '<div id="faq-answer-' + idx + '" class="faq-answer" role="region" aria-labelledby="faq-button-' + idx + '">' +
                '<div class="faq-answer-content">' + faq.answer + '</div>' +
            '</div>' +
        '</div>'
    ).join('');
}

function toggleFAQ(idx) {
    const answer = document.getElementById('faq-answer-' + idx);
    const icon = document.getElementById('faq-icon-' + idx);
    const button = answer.previousElementSibling; // Get the button element
    
    const isExpanded = button.getAttribute('aria-expanded') === 'true';
    
    if (isExpanded) {
        // Collapse
        answer.style.maxHeight = '0px';
        icon.textContent = '+';
        button.setAttribute('aria-expanded', 'false');
    } else {
        // Expand
        answer.style.maxHeight = answer.scrollHeight + 'px';
        icon.textContent = '−'; // minus sign
        button.setAttribute('aria-expanded', 'true');
    }
}

// Global variable to track current viewing flight
let currentViewingFlightFilename = null;

// Viewing Flight Information Box Functions
function showViewingFlight(flight) {
    const box = document.getElementById('viewingFlightBox');
    const title = document.getElementById('viewingFlightTitle');
    const date = document.getElementById('viewingFlightDate');
    const sa = document.getElementById('viewingFlightSA');
    const reg = document.getElementById('viewingFlightReg');
    const filename = document.getElementById('viewingFlightFilename');
    const size = document.getElementById('viewingFlightSize');
    const download = document.getElementById('viewingFlightDownload');
    
    // Store current flight filename globally
    currentViewingFlightFilename = flight.filename;
    
    // Populate flight information
    title.textContent = 'Viewing Flight: ' + (flight.registration || 'Unknown');
    date.textContent = flight.date || '-';
    sa.textContent = utcToSaTime(flight.date, flight.time);
    reg.textContent = flight.registration || '-';
    document.getElementById('viewingFlightOwner').textContent = flight.owner || '-';
    filename.textContent = flight.filename || '-';
    size.textContent = flight.fileSizeMB ? flight.fileSizeMB + ' MB' : '-';
    
    // Update download button
    download.onclick = () => downloadKML(flight.filename);
    
    // Show the box
    box.style.display = 'block';
}

function closeViewingFlight() {
    document.getElementById('viewingFlightBox').style.display = 'none';
    
    // Clear the current viewing flight filename
    currentViewingFlightFilename = null;
    
    // Clear the last viewed filename to remove highlighting
    lastViewedFilename = null;
    
    // Re-render table to remove highlighting
    renderTable();
    
    // Remove flight layer from map
    if (currentFlightLayer) {
        map.removeLayer(currentFlightLayer);
        currentFlightLayer = null;
    }
    
    // Show instruction overlay again
    const existingOverlay = document.getElementById('instructionOverlay');
    if (!existingOverlay) {
        const instructionDiv = document.createElement('div');
        instructionDiv.id = 'instructionOverlay';
        instructionDiv.innerHTML = '<div style="text-align: center; line-height: 1.4;"><div style="font-size: 18px; margin-bottom: 8px;">🗺️ Flight Tracking Map</div><div style="font-size: 14px; margin-bottom: 12px;">Scroll down to view flights</div><div style="font-size: 12px; color: #ccc;">Click the 👀 button on any flight to see its path</div></div>';
        instructionDiv.style.cssText = 'position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); background: rgba(0,0,0,0.8); color: white; padding: 25px 35px; border-radius: 12px; z-index: 1000; font-size: 14px; font-weight: 500; box-shadow: 0 6px 20px rgba(0,0,0,0.4); max-width: 300px;';
        map.getContainer().appendChild(instructionDiv);
    }
    
    // Disable map scroll zoom so users can scroll the page
    map.scrollWheelZoom.disable();
}

    function jumpToTable() {
        // Scroll to the specific flight row using lastViewedFilename
        if (lastViewedFilename) {
            const rowElement = document.getElementById('flight-' + lastViewedFilename);
            if (rowElement) {
                rowElement.scrollIntoView({ behavior: 'smooth', block: 'center' });
                // Flash effect to highlight the row
                rowElement.style.transition = 'background-color 0.5s';
                rowElement.style.backgroundColor = '#fff7e6';
                setTimeout(() => {
                    rowElement.style.backgroundColor = '#e6f7ff';
                }, 1000);
            }
        } else {
            // Fallback: scroll to table container if no specific flight
            const tableContainer = document.getElementById('tableContainer');
            tableContainer.scrollIntoView({ behavior: 'smooth' });
        }
    }
    
    function takeAction() {
        if (currentViewingFlightFilename) {
            reportFlight(currentViewingFlightFilename);
        } else {
            alert('No flight selected. Please click the eye button on a flight first.');
        }
    }

// Format and display last updated timestamp
function formatRelativeTime(dateString) {
    const now = new Date();
    const date = new Date(dateString);
    const diffMs = now - date;
    const diffMins = Math.floor(diffMs / (1000 * 60));
    const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
    const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
    
    if (diffMins < 1) return 'just now';
    if (diffMins < 60) return `${diffMins} minute${diffMins === 1 ? '' : 's'} ago`;
    if (diffHours < 24) return `${diffHours} hour${diffHours === 1 ? '' : 's'} ago`;
    if (diffDays < 7) return `${diffDays} day${diffDays === 1 ? '' : 's'} ago`;
    
    // For older dates, show the actual date
    return date.toLocaleDateString('en-US', { 
        month: 'short', 
        day: 'numeric',
        year: date.getFullYear() !== now.getFullYear() ? 'numeric' : undefined
    });
}

function formatFlightDate(dateString) {
    if (!dateString) return 'No data';
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', { 
        month: 'short', 
        day: 'numeric',
        year: date.getFullYear() !== new Date().getFullYear() ? 'numeric' : undefined
    });
}

// Update timestamp display
document.addEventListener('DOMContentLoaded', function() {
    const siteUpdateEl = document.getElementById('siteUpdateTime');
    const flightDataEl = document.getElementById('flightDataTime');
    
    if (siteUpdateEl && window.buildTimestamp) {
        const relativeTime = formatRelativeTime(window.buildTimestamp);
        siteUpdateEl.textContent = `Site updated ${relativeTime}`;
    }
    
    if (flightDataEl && window.latestFlightDate) {
        const flightDate = formatFlightDate(window.latestFlightDate);
        flightDataEl.textContent = ` • Flight data up to ${flightDate}`;
    }
    
    // Load flight data and initialize the app
    loadFlightData();
});
